# -----------------------------------------------------------------------------------
#                     Windows OS
# -----------------------------------------------------------------------------------

# Nothing to configure

# -----------------------------------------------------------------------------------
#                           Ubuntu OS
# -----------------------------------------------------------------------------------

- name: Preparing a VM with ubuntu OS
  hosts: ubuntu_vm
  tasks:

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
      become: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        force_apt_get: yes
      become: yes

    - name: Create a Directory /home/student/workshop
      file:
        path: /home/student/workshop
        state: directory
        mode: 0755
        owner: student
        group: student
      become: yes

    - name: Get zip from http://192.168.40.15/datasets.zip
      get_url:
        url: http://192.168.40.15/datasets.zip
        dest: /tmp
        mode: 0755
        group: student
        owner: student
      become: yes

    - name: Install zip
      apt:
        name: zip
        state: present
        update_cache: True
      become: yes

    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /tmp/datasets.zip
        dest: /home/student/workshop
        remote_src: yes

# ==========================================================
# Sources used:
#   for create dir, get zip and install zip:
#     - https://www.middlewareinventory.com/blog/ansible-get_url-examples-how-to-download-file-from-url/
#   for unarchive file:
#     - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html

